name: actions-examples

on:
  push:
    branches: [ main ]

env:
  CUSTOM_ENV: ${GITHUB_REF#refs/}

jobs:
  custom-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: python-script
        uses: ./.github/actions/python
        with:
          script: ./.github/actions/python/script.py
          arg-1: arg-1
          arg-2: arg-2

      - run: echo $CUSTOM_ENV
